services:
  solid-postgres:
    container_name: 'solid-postgres'
    image: 'postgres:17'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: 'solid_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - db_data:/var/lib/postgresql/data

  solid-pgadmin:
    container_name: 'solid-pgadmin'
    image: 'dpage/pgadmin4:9.4'
    ports:
      - '5051:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'rs7951006@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    depends_on:
      - solid-postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:


