services:
  solid-postgres:
    container_name: 'solid-postgres'
    image: 'postgres:17'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'solid-db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - db_data:/var/lib/postgresql/data

  solid-pgadmin:
    container_name: 'solid-pgadmin'
    image: 'dpage/pgadmin4:9.4'
    ports:
      - '5051:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'rs7951006@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    depends_on:
      - solid-postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  solid-mongo:
    container_name: 'solid-mongo'
    image: 'mongo'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    volumes:
      - mongodb_data:/data/db

volumes:
  db_data:
  pgadmin_data:
  mongodb_data:

